--unzip download
--  unzip 000##########.zip -x meta.xml verbatim.txt citations.txt multimedia.txt rights.txt

--remove first line
--  sed -i '1d' occurrence.txt


--Replace backslashes in some text fields
--  sed -i 's.\\./.g' occurrence.txt

--Table to store the original contents of occurrence
DROP TABLE IF EXISTS gbif_occ CASCADE;
-- Dont log these tables to speed up inserts
CREATE UNLOGGED TABLE gbif_occ(
    gbifID text,
    abstract text,
    accessRights text,
    accrualMethod text,
    accrualPeriodicity text,
    accrualPolicy text,
    alternative text,
    audience text,
    available text,
    bibliographicCitation text,
    conformsTo text,
    contributor text,
    coverage text,
    created text,
    creator text,
    date text,
    dateAccepted text,
    dateCopyrighted text,
    dateSubmitted text,
    description text,
    educationLevel text,
    extent text,
    format text,
    hasFormat text,
    hasPart text,
    hasVersion text,
    identifier text,
    instructionalMethod text,
    isFormatOf text,
    isPartOf text,
    isReferencedBy text,
    isReplacedBy text,
    isRequiredBy text,
    isVersionOf text,
    issued text,
    language text,
    license text,
    mediator text,
    medium text,
    modified text,
    provenance text,
    publisher text,
    _references text,
    relation text,
    replaces text,
    requires text,
    rights text,
    rightsHolder text,
    source text,
    spatial text,
    subject text,
    tableOfContents text,
    temporal text,
    title text,
    type text,
    valid text,
    institutionID text,
    collectionID text,
    datasetID text,
    institutionCode text,
    collectionCode text,
    datasetName text,
    ownerInstitutionCode text,
    basisOfRecord text,
    informationWithheld text,
    dataGeneralizations text,
    dynamicProperties text,
    occurrenceID text,
    catalogNumber text,
    recordNumber text,
    recordedBy text,
    individualCount text,
    organismQuantity text,
    organismQuantityType text,
    sex text,
    lifeStage text,
    reproductiveCondition text,
    behavior text,
    establishmentMeans text,
    occurrenceStatus text,
    preparations text,
    disposition text,
    associatedReferences text,
    associatedSequences text,
    associatedTaxa text,
    otherCatalogNumbers text,
    occurrenceRemarks text,
    organismID text,
    organismName text,
    organismScope text,
    associatedOccurrences text,
    associatedOrganisms text,
    previousIdentifications text,
    organismRemarks text,
    materialSampleID text,
    eventID text,
    parentEventID text,
    fieldNumber text,
    eventDate text,
    eventTime text,
    startDayOfYear text,
    endDayOfYear text,
    year text,
    month text,
    day text,
    verbatimEventDate text,
    habitat text,
    samplingProtocol text,
    samplingEffort text,
    sampleSizeValue text,
    sampleSizeUnit text,
    fieldNotes text,
    eventRemarks text,
    locationID text,
    higherGeographyID text,
    higherGeography text,
    continent text,
    waterBody text,
    islandGroup text,
    island text,
    countryCode text,
    stateProvince text,
    county text,
    municipality text,
    locality text,
    verbatimLocality text,
    verbatimElevation text,
    verbatimDepth text,
    minimumDistanceAboveSurfaceInMeters text,
    maximumDistanceAboveSurfaceInMeters text,
    locationAccordingTo text,
    locationRemarks text,
    decimalLatitude text,
    decimalLongitude text,
    coordinateUncertaintyInMeters text,
    coordinatePrecision text,
    pointRadiusSpatialFit text,
    verbatimCoordinateSystem text,
    verbatimSRS text,
    footprintWKT text,
    footprintSRS text,
    footprintSpatialFit text,
    georeferencedBy text,
    georeferencedDate text,
    georeferenceProtocol text,
    georeferenceSources text,
    georeferenceVerificationStatus text,
    georeferenceRemarks text,
    geologicalContextID text,
    earliestEonOrLowestEonothem text,
    latestEonOrHighestEonothem text,
    earliestEraOrLowestErathem text,
    latestEraOrHighestErathem text,
    earliestPeriodOrLowestSystem text,
    latestPeriodOrHighestSystem text,
    earliestEpochOrLowestSeries text,
    latestEpochOrHighestSeries text,
    earliestAgeOrLowestStage text,
    latestAgeOrHighestStage text,
    lowestBiostratigraphicZone text,
    highestBiostratigraphicZone text,
    lithostratigraphicTerms text,
    _group text,
    formation text,
    member text,
    bed text,
    identificationID text,
    identificationQualifier text,
    typeStatus text,
    identifiedBy text,
    dateIdentified text,
    identificationReferences text,
    identificationVerificationStatus text,
    identificationRemarks text,
    taxonID text,
    scientificNameID text,
    acceptedNameUsageID text,
    parentNameUsageID text,
    originalNameUsageID text,
    nameAccordingToID text,
    namePublishedInID text,
    taxonConceptID text,
    scientificName text,
    acceptedNameUsage text,
    parentNameUsage text,
    originalNameUsage text,
    nameAccordingTo text,
    namePublishedIn text,
    namePublishedInYear text,
    higherClassification text,
    kingdom text,
    phylum text,
    class text,
    _order text,
    family text,
    genus text,
    subgenus text,
    specificEpithet text,
    infraspecificEpithet text,
    taxonRank text,
    verbatimTaxonRank text,
    vernacularName text,
    nomenclaturalCode text,
    taxonomicStatus text,
    nomenclaturalStatus text,
    taxonRemarks text,
    datasetKey text,
    publishingCountry text,
    lastInterpreted text,
    elevation text,
    elevationAccuracy text,
    depth text,
    depthAccuracy text,
    distanceAboveSurface text,
    distanceAboveSurfaceAccuracy text,
    issue text,
    mediaType text,
    hasCoordinate text,
    hasGeospatialIssues text,
    taxonKey text,
    acceptedTaxonKey text,
    kingdomKey text,
    phylumKey text,
    classKey text,
    orderKey text,
    familyKey text,
    genusKey text,
    subgenusKey text,
    speciesKey text,
    species text,
    genericName text,
    acceptedScientificName text,
    typifiedName text,
    protocol text,
    lastParsed text,
    lastCrawled text,
    repatriated text);

--insert to table
\copy gbif_occ FROM occurrence.txt;



--insert into occurrence table for system
insert into mg_occurrences 
    (
        occurrence_source,
        occurrenceid,
        gbifid,
        datasetid,
        datasetName,
        basisofrecord,
        informationwithheld,
        datageneralizations,
        eventdate,
        verbatimeventdate,
        highergeography,
        continent,
        waterbody,
        islandgroup,
        island,
        countrycode,
        stateprovince,
        county,
        municipality,
        locality,
        verbatimlocality,
        verbatimelevation,
        locationremarks,
        decimallatitude,
        decimallongitude,
        coordinateuncertaintyinmeters,
        coordinateprecision,
        pointradiusspatialfit,
        verbatimcoordinatesystem,
        verbatimsrs,
        georeferencedby,
        georeferenceddate,
        georeferenceprotocol,
        georeferencesources,
        georeferenceverificationstatus,
        georeferenceremarks,
        geologicalcontextid,
        earliesteonorlowesteonothem,
        latesteonorhighesteonothem,
        earliesteraorlowesterathem,
        latesteraorhighesterathem,
        earliestperiodorlowestsystem,
        latestperiodorhighestsystem,
        earliestepochorlowestseries,
        latestepochorhighestseries,
        earliestageorloweststage,
        latestageorhigheststage,
        lowestbiostratigraphiczone,
        highestbiostratigraphiczone,
        lithostratigraphicterms,
        typestatus,
        taxonid,
        scientificname,
        acceptednameusage,
        higherclassification,
        kingdom,
        phylum,
        class,
        _order,
        family,
        genus,
        subgenus,
        specificepithet,
        infraspecificepithet,
        taxonrank,
        taxonremarks,
        datasetkey,
        elevation,
        elevationaccuracy,
        issue,
        hascoordinate,
        hasgeospatialissues,
        taxonkey,
        acceptedtaxonkey,
        kingdomkey,
        phylumkey,
        classkey,
        orderkey,
        familykey,
        genuskey,
        subgenuskey,
        specieskey,
        species,
        genericname,
        acceptedscientificname,
        lastparsed,
        recordedby
        )
    (
        SELECT 
            'https://doi.org/10.15468/dl.zmhder' as occurrence_source,
            case when occurrenceID = '' then null else occurrenceID end as occurrenceID,
            gbifID::bigint,
            datasetid,
            datasetName,
            basisofrecord,
            informationwithheld,
            datageneralizations,
            case when eventdate = '' then null else eventdate::date end as eventdate,
            verbatimeventdate,
            highergeography,
            continent,
            waterbody,
            islandgroup,
            island,
            case when countrycode = '' then null else countrycode end as countrycode,
            case when stateprovince = '' then null else stateprovince end as stateprovince,
            county,
            municipality,
            case when locality = '' then null else locality end as locality,
            verbatimlocality,
            verbatimelevation,
            locationremarks,
            CASE WHEN decimallatitude = '' then null else decimallatitude::float end as decimallatitude,
            CASE WHEN decimallongitude = '' then null else decimallongitude::float end as decimallongitude,
            case when coordinateuncertaintyinmeters = '' then null else coordinateuncertaintyinmeters end as coordinateuncertaintyinmeters,
            coordinateprecision,
            pointradiusspatialfit,
            verbatimcoordinatesystem,
            verbatimsrs,
            georeferencedby,
            georeferenceddate,
            georeferenceprotocol,
            georeferencesources,
            georeferenceverificationstatus,
            georeferenceremarks,
            geologicalcontextid,
            earliesteonorlowesteonothem,
            latesteonorhighesteonothem,
            earliesteraorlowesterathem,
            latesteraorhighesterathem,
            earliestperiodorlowestsystem,
            latestperiodorhighestsystem,
            earliestepochorlowestseries,
            latestepochorhighestseries,
            earliestageorloweststage,
            latestageorhigheststage,
            lowestbiostratigraphiczone,
            highestbiostratigraphiczone,
            lithostratigraphicterms,
            typestatus,
            taxonid,
            case when scientificname = '' then null else scientificname end as scientificname,
            acceptednameusage,
            higherclassification,
            case when kingdom = '' then null else kingdom end as kingdom,
            case when phylum = '' then null else phylum end as phylum,
            case when class = '' then null else class end as class,
            case when _order = '' then null else _order end as _order,
            case when family = '' then null else family end as family,
            case when genus = '' then null else genus end as genus,
            case when subgenus = '' then null else subgenus end as subgenus,
            case when specificepithet = '' then null else specificepithet end as specificepithet,
            case when infraspecificepithet = '' then null else infraspecificepithet end as infraspecificepithet,
            case when taxonrank = '' then null else taxonrank end as taxonrank,
            taxonremarks,
            datasetkey,
            elevation,
            elevationaccuracy,
            case when issue = '' then null else issue end as issue,
            hascoordinate,
            hasgeospatialissues,
            taxonkey,
            acceptedtaxonkey,
            kingdomkey,
            phylumkey,
            classkey,
            orderkey,
            familykey,
            genuskey,
            subgenuskey,
            specieskey,
            case when species = '' then null else species end as species,
            genericname,
            acceptedscientificname,
            lastparsed,
            case when recordedby = '' then null else recordedby end as recordedby
        FROM
            gbif_occ
        );



DROP TABLE gbif_occ;



---------
--Multimedia 

--sed -i '1d' multimedia.txt


--Replace backslashes in some text fields
--  sed -i 's.\\./.g' multimedia.txt

\copy mg_occurrences_media (gbifid, type, format, identifier, _references, title, description, created, creator, contributor, publisher, audience, source, license, rightsHolder) from 'multimedia.txt';
UPDATE mg_occurrences_media m SET mg_occurrenceid = o.mg_occurrenceid FROM mg_occurrences o WHERE m.gbifid = o.gbifid;